apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hk-namespace
  name: hk-nginx-deployment
  labels:
    app: hknginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hknginx
  template:
    metadata:
      labels:
        app: hknginx
    spec:
      containers:
      - name: hk-nginx
        #image: 590184007385.dkr.ecr.us-east-1.amazonaws.com/hk_image:latest
        #image: 851725635917.dkr.ecr.us-east-1.amazonaws.com/hk-ecr-repo:v1.0.0
        image: 211125530440.dkr.ecr.us-east-1.amazonaws.com/my-repo:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
