apiVersion: v1
kind: Service
metadata:
  namespace: hk-namespace
  name: hk-lb-service
spec:
  selector:
    app: hknginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
