name: Deploy Docker Image to Amazon EKS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-east-1
  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
  EKS_CLUSTER_NAME: CLUSTER_NAME
  
permissions:
  contents: read

jobs:
  deploy-to-eks:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Install Kubectl
      id: kubectl-install
      uses: Azure/setup-kubectl@v4.0.0

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region ${{ env.AWS_REGION }}
    - name: Deploy to EKS
      run: |
        kubectl apply -f manifests/deployment.yaml
        kubectl apply -f manifests/service.yaml
    
