name: Docker Image CI
on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  
jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Optional: Set up Docker Buildx (only if building multi-platform images)
    - name: Set up Docker Buildx (optional)
      uses: docker/setup-buildx-action@v3.7.1

    - name: Build docker image
      run: |
        docker build -t hk_image:v1 .

    - name: Filter docker image
      run: |
        docker images --filter reference=hk_image

    - name: "Configure AWS Credentials"
      id: Configure-AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Authenticate to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Tag the Image
      run: |
        docker tag hk_image:v1 ${{ secrets.ECR_REPOSITORY }}:latest
        docker tag hk_image:v1 ${{ secrets.ECR_REPOSITORY }}:v1.0.0

    - name: Push the Image to Aws ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REPOSITORY }}:v1.0.0

    - name: Image cleanup
      if: always()
      run: |
        docker rmi ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:v1.0.0 || true

    # Save the built image as an artifact to be used by the next job
    #- name: Upload Docker Image as Artifact
    #  uses: actions/upload-artifact@v4.4.3
    #  with:
    #    name: docker-image
    #    path: ./hk_image:v1

  trivy_scan:
    runs-on: ubuntu-latest
    needs: docker_build  # This job will run after the "docker_build" job is completed

    steps:
    - name: "Configure AWS Credentials"
      id: Configure-AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Authenticate to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Aqua Security Trivy Scan
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: ${{ secrets.ECR_REPOSITORY }}:latest
        scan-type: image
        severity: 'HIGH,CRITICAL'
        format: 'table'
        vuln-type: 'os,library'

    - name: Check if SARIF file exists
      run: |
        if [ -f "trivy-results.sarif" ]; then
          echo "SARIF file exists"
        else
          echo "SARIF file does not exist"
          exit 1
        fi
  
    - name: Check if SARIF file exists
      run: |
        ls -l trivy-results.sarif
        
    # Upload Trivy Scan Results to GitHub Security Tab
    #- name: Upload Trivy Scan Results to GitHub Security Tab
    #  uses: github/codeql-action/upload-sarif@v3
    #  with:
    #    sarif_file: trivy-vuln-results.sarif
        
    # Upload Trivy scan results as an artifact
    #- name: Upload Trivy Scan Results
    #  uses: actions/upload-artifact@v4.4.3
    #  with:
    #    name: trivy-vuln-results
    #    path: ${{ github.workspace }}/trivy-vuln-results.json
     #   retention-days: 10

    - name: Image cleanup
      if: always()
      run: |
        docker rmi ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:v1.0.0 || true
